// frameworks/next/src/app/IsomorphicDompurifyTest.tsx
import DOMPurify from "isomorphic-dompurify";

const IsomorphicDompurifyTest = () => {
  return (
    <div>
      {DOMPurify.sanitize(`<a onclick="javascript:alert('test')" href="https://github.com/kkomelin/isomorphic-dompurify-playground">Test</a>`)}
    </div>
  );
};

export default IsomorphicDompurifyTest;

// frameworks/angular/src/app/isomorphic-dompurify-test/isomorphic-dompurify-test.ts
import { Component } from '@angular/core';
import DOMPurify from 'isomorphic-dompurify';

@Component({
  selector: 'app-isomorphic-dompurify-test',
  template: `<div>{{ sanitized }}</div>`,
})
export class IsomorphicDompurifyTest {
  sanitized = DOMPurify.sanitize(
    `<a onclick="javascript:alert('test')" href="https://angular">Test</a>`
  );
}
